version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: WMF 5
environment:
  DevDeploymentURI:
    secure: Povc/ZMJNsRYfKgrXCQnHb8U0zLY8K3j8nf/rSoUwnqy4NwO03pdd+lK9kBhKuOW+mHFA7s5xy+T+zUxwPQhsdH+mvOsW5rR5+hzkO1pSF4bCio+0XYELzNvlBMbDy5eWpgPNguVqT5C216H/L7SpA==
  ProdDeploymentURI:
    secure: Povc/ZMJNsRYfKgrXCQnHb8U0zLY8K3j8nf/rSoUwnqy4NwO03pdd+lK9kBhKuOWYOi/vyrq8u2Su9wqc3iNDIYcaNxcwP3ucCDItASrDIQv0wD4uq+LlDnwH6NJ9z6xjtkjNivG2FcF6KAUdjVaCA==
clone_folder: c:\git\RunbookExample
init:
- ps: git clone -q --branch="$($env:APPVEYOR_REPO_BRANCH)" https://github.com/randorfer/SCOrchDev c:\git\scorchdev
- ps: $env:PSModulePath = "$($env:PSModulePath);c:\git\ScorchDev\PowerShellModules;c:\git\RunbookExample\PowerShellModules"
nuget:
  disable_publish_on_pr: true
build: false
test_script:
- ps: >-
    & c:\git\SCOrchDev\Profile\profile.ps1

    $res = Invoke-Pester -Path "$($env:APPVEYOR_BUILD_FOLDER)\Tests" -OutputFormat NUnitXml -OutputFile c:\TestsResults.xml -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", "c:\TestsResults.xml")

    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
deploy_script:
- ps: >-
    & c:\git\SCOrchDev\Profile\profile.ps1

    & c:\git\SCOrchDev\AppVeyor\deploy.ps1
